name: ESLint

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        run: |
          echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})"
      - name: Debug
        run: |
          echo "${{ github.event.pull_request.base.sha }}"
          echo "${{ github.sha }}"
