name: ESLint

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint:all

      - name: Get changed files
        run: |
          echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})"
      - name: Debug
        run: |
          echo "${{ github.event.pull_request.base.sha }}"
          echo "${{ github.sha }}"

      - run: echo "🍏 This job's status is ${{ job.status }}."
